### ISSUE TITLE
CUDA fails after installation

### ISSUE THREAD

**Issue by sergei-sh** [torch/cunn#475]
Installed torch, cuda, cunn.

test.py
```
import lutorpy as lua
lua.require('cunn')
```

Output:
```
THCudaCheck FAIL file=/home/serj/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    lua.require('cunn')
  File "/home/serj/work/beautytorch/venv/local/lib/python2.7/site-packages/lutorpy/__init__.py", line 112, in require
    ret = luaRuntime.require(module_name)
  File "lutorpy/_lupa.pyx", line 318, in lutorpy._lupa.LuaRuntime.require (lutorpy/_lupa.c:6189)
  File "lutorpy/_lupa.pyx", line 1658, in lutorpy._lupa.call_lua (lutorpy/_lupa.c:25877)
  File "lutorpy/_lupa.pyx", line 1667, in lutorpy._lupa.execute_lua_call (lutorpy/_lupa.c:25987)
  File "lutorpy/_lupa.pyx", line 1620, in lutorpy._lupa.raise_lua_error (lutorpy/_lupa.c:25297)
lutorpy._lupa.LuaError: cuda runtime error (30) : unknown error at /home/serj/torch/extra/cutorch/lib/THC/THCGeneral.c:66
```

Tests fail the same way:

`(venv) serj@venus ~/work/beautytorch/beauty.torch $ luajit -l cunn -e 'cunn.test()'
THCudaCheck FAIL file=/home/serj/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
luajit: cuda runtime error (30) : unknown error at /home/serj/torch/extra/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: at 0x7f73b2cd5b00
	[C]: in function 'require'
	/home/serj/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
	[C]: in function 'require'
	/home/serj/torch/install/share/lua/5.1/cunn/init.lua:3: in main chunk
	[C]: at 0x0046b7a0
	[C]: at 0x00406670
`
Related code:

`void THCudaInit(THCState* state)
{
  if (!state->cudaDeviceAllocator) {
    state->cudaDeviceAllocator = &defaultDeviceAllocator;
  }
  if (!state->cudaHostAllocator) {
    state->cudaHostAllocator = &THCudaHostAllocator;
  }
  if (!state->cudaUVAAllocator) {
    state->cudaUVAAllocator = &THCUVAAllocator;
  }

  int numDevices = 0;
  THCudaCheck(cudaGetDeviceCount(&numDevices)); // FAILS HERE!!!
`
Maybe the problem relates to the fact that my GPU is not NVidia, but lua.require("cunn") is needed as a part of 3-rd party project which I'm trying to use

**Comment by tastyminerals** [comment]
You should have Nvidia GPU if you work with any deep learning framework these days. Yes, you must have Nvidia GPU to run torch on GPU. 
Consider closing the issue please.
